from manim import *
import manim

class BlackScholesModel(Scene):
    def construct(self):

        eq1 = MathTex(r"C = N(d_1)S_t - N(d_2)Ke^{-rt}")
        eq1.scale(2)
        self.add(eq1)
        framebox = SurroundingRectangle(eq1, buff=0.5)
        # self.play(Write(framebox))
        self.add(framebox)
        self.wait()

        ask = Text('Do You Know Me?', color=RED, font_size=96)
        self.remove(eq1)
        self.play(Transform(framebox, ask))
        self.wait(2)
        self.clear()

        eq1 = MathTex(r"C = N(d_1)S_t - N(d_2)Ke^{-rt}")
        eq2 = MathTex(r"\text{where } d_1 = \frac{\ln(\frac{S_t}{K}) + (r + \frac{\sigma}{2})t}{\sigma\sqrt{t}}")
        eq3 = MathTex(r"\text{and } d_2 = d_1 - \sigma\sqrt{t}")
        eq4 = MathTex(r"C = \text{call option price}")
        eq5 = MathTex(r"N = \text{CDF of the normal distribution}")
        eq6 = MathTex(r"S_t = \text{spot price of an asset}")
        eq7 = MathTex(r"K = \text{strike price}")
        eq8 = MathTex(r"r = \text{risk-free interest rate}")
        eq9 = MathTex(r"t = \text{time to maturity}")
        eq10 = MathTex(r"\sigma = \text{time to maturity}")
        eq_group = VGroup(eq1, eq2, eq3, eq4, eq5, eq6, eq7, eq8, eq9, eq10).arrange(direction=DOWN, buff=0.36, aligned_edge=LEFT).scale(0.9)

        eq1.scale(1.5)
        self.add(eq1)
        self.play(Circumscribe(eq1))
        boxeq1 = SurroundingRectangle(eq1, buff=0.15)
        self.play(Write(boxeq1))
        self.wait()
        self.play(Indicate(eq2))
        self.wait()
        self.play(Indicate(eq3))
        self.wait()
        self.play(Indicate(eq4))
        self.wait()
        self.play(Indicate(eq5))
        self.wait()
        self.play(Indicate(eq6))
        self.wait()
        self.play(Indicate(eq7))
        self.wait()
        self.play(Indicate(eq8))
        self.wait()
        self.play(Indicate(eq9))
        self.wait()
        self.play(Indicate(eq10))
        self.wait()

        self.wait(3)
        self.remove(boxeq1)
        # self.play(Unwrite(eq_group))

        # self.clear()
        t = Text('By DevPool', color=RED)
        self.play(Transform(eq_group, t))
        self.play(FocusOn(t))
        self.wait()
