from manim import *
import manim

class RuleOf72(Scene):
    def construct(self):
        t = Text('What Is "Rule Of 72" ?', gradient=(RED, ORANGE, BLUE, PURPLE), font_size=96)
        self.play(Write(t))
        self.play(Unwrite(t))

        title = Title(f"It Is Finance Estimates")
        equation = MathTex(r"\text{Year Of Double} = \frac{72}{\text{Interest Rate}}")

        self.play(Create(title))
        self.play(Write(equation))

        framebox = SurroundingRectangle(equation, buff=0.5)
        self.play(Write(framebox))

        self.wait(3)
        self.clear()

        example1 = MathTex(r"\text{1. At 8\% interest, your money takes } \frac{72}{8} = 9 \text{ years to double}")
        example2 = MathTex(r"\text{2. If GDP grows at 5\% a year, economy doubles in } \frac{72}{5} = 14 \text{ years}")
        example3 = MathTex(r"\text{3. If inflation rates go from 2\% to 3\%, your money will lose half its value in 24 years instead of 36.}")
        example1.scale(0.6)
        example2.scale(0.6)
        example3.scale(0.6)
        example2.next_to(example1, DOWN)
        example3.next_to(example2, DOWN)

        self.play(Write(example1))
        self.wait(1.5)
        self.play(Write(example2))
        self.wait(1.5)
        self.play(Write(example3))
        self.wait(2.5)
        self.clear()

        question = Text("But Why Is 72 ? ", t2c={'72': RED})
        self.play(Create(question))
        self.wait(2.0)

        question_topleft = Text("But Why Is 72 ? ", t2c={'72': RED}).scale(0.7)
        question_topleft.to_corner(UP + LEFT)
        self.play(Transform(question, question_topleft))
        self.wait()

        t1 = Tex("Suppose we have \$1 and a yearly interest rate R.\nAfter one year we have:")
        t2 = MathTex(r"\rightarrow 1 * (1 + R)", color=YELLOW)
        t3 = Tex(r"E.g at 10\% interest, we'd have \$1 * (1 + 0.1) = \$1.10 at the end of year")
        t4 = Tex(r"After 2 years, we's have")
        t5 = MathTex(r"\rightarrow 1 * (1 + R) * (1 + R) = 1 * (1 + R)^2", color=YELLOW)
        t6 = MathTex(r"\text{And at 10\% interest, we have }\$1 * (1.1)^2 = \$1.21\text{ at the end of year 2.}")
        t7 = Tex(r"Extending this year after year, after N years we have")
        t8 = MathTex(r"\rightarrow 1 * (1 + R)^N", color=YELLOW)
        x = VGroup(t1, t2, t3, t4, t5, t6, t7, t8).arrange(direction=DOWN, aligned_edge=LEFT).scale(0.7)
        # self.play(ShowIncreasingSubsets(x, run_time=5))
        self.play(Write(x[0]))
        self.wait()
        self.play(Indicate(t2))
        self.wait()
        self.play(Write(x[2]))
        self.wait()
        self.play(Write(x[3]))
        self.wait()
        self.play(Indicate(x[4]))
        self.wait()
        self.play(Write(x[5]))
        self.wait()
        self.play(Write(x[6]))
        self.wait()
        self.play(Indicate(x[7]))
        self.wait(3)
        self.play(Unwrite(x))

        self.clear()
        q1 = Text("How long it takes to double?", t2c={'double': RED})
        self.play(Create(q1))
        self.wait()
        q2 = Text("How long it takes to double?", t2c={'double': RED}).scale(0.7)
        q2.to_corner(UP + LEFT)
        self.play(Transform(q1, q2))
        self.wait()

        eq1 = MathTex(r"1 * (1 + R)^N = 2")
        eq2 = MathTex(r"(1 + R)^N = 2")
        eq3 = MathTex(r"ln((1 + R)^N) = ln(2) \text{ (natural log of both sides)}")
        eq4 = MathTex(r"N * ln(1 + R) = 0.693")
        eq5 = MathTex(r"N * R = 0.693 \text{ (For small R, } ln(1+R) \approx R)")
        eq6 = MathTex(r"N = 0.693 / R")
        eq7 = MathTex(r"N = 69.3 / R\% \text{ (Multiply right hand side by 100)}", color=YELLOW_C)
        eq8 = Text("69.3 is nice but not easily divisible. 72 is closeby, and have many more factors (2, 3, 4, 6, 12, ...)", t2c={'72': RED, '69.3': YELLOW}).scale(0.7)
        eq9 = Text("So the rule of 72 it is", color=RED)
        eq_group = VGroup(eq1, eq2, eq3, eq4, eq5, eq6, eq7, eq8, eq9).arrange(direction=DOWN, aligned_edge=LEFT).scale(0.7)
        # self.play(ShowIncreasingSubsets(eq_group, run_time=5))
        self.play(Indicate(eq1))
        self.wait()
        self.play(Indicate(eq2))
        self.wait()
        self.play(Indicate(eq3))
        self.wait()
        self.play(Indicate(eq4))
        self.wait()
        self.play(Indicate(eq5))
        self.wait()
        self.play(Indicate(eq6))
        self.wait()
        self.play(Indicate(eq7))
        self.wait()
        self.play(Indicate(eq8))
        self.wait()
        self.play(Indicate(eq9))
        self.wait(3)
        self.play(Unwrite(eq_group))

        self.clear()
        t = Text('Thanks for watching and happy learning!', gradient=(RED, BLUE, PURPLE))
        self.play(Write(t))
        self.wait()
